#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.context = "personal_ci"
    args.mode = "manual"
    args.cluster = false

    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.f11627e98c6cdb77f5e9d00c4ca221b32b6b6908.name = "2024.12.10~ynh1"
