#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL INCUS
#=================================================
ynh_script_progression "Installing Incus... (this make take a long time!)"

if ! yunohost app list --output-as json --quiet | jq -e '.apps[] | select(.id == "incus")' >/dev/null; then
    yunohost app install --force https://github.com/YunoHost-Apps/incus_ynh
fi

setup_incus

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

_git_clone_or_pull "$install_dir/yunorunner"
_git_clone_or_pull "$install_dir/package_check" https://github.com/YunoHost/package_check

chown "$app:www-data" "$install_dir" "$install_dir/yunorunner"
chown -R "$app:www-data" "$install_dir/yunorunner/results"

# Allow system user to execute ciclic
chmod ug+x "$install_dir/yunorunner/ciclic"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd "$install_dir"
    python3 -m venv venv
    venv/bin/pip install --upgrade pip
    venv/bin/pip install -r yunorunner/requirements.txt
    # package_check dep not in apt
    venv/bin/pip install imgkit
popd

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding a config file..."

if [ $mode = "auto" ]; then
    auto="True"
else
    auto="False"
fi

ynh_config_add --template="yunorunner.config.py" --destination="$install_dir/yunorunner/config.py"

#=================================================
# FINISH INSTALL
#=================================================
ynh_script_progression "Run Yunorunner's finish_install script..."

if [ "$context" == "official_infra" ] && ynh_in_ci_tests; then
    tweak_yunohost
fi

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="$app daemon for YunoRunner"

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path="systemd" --timeout=30

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
